api:
  osm:
    url: https://api.openstreetmap.org/

server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        stat: debug
        cache: debug
        SQL: debug
        type:
          descriptor:
            sql: trace
    sql: debug
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rail
    username: postgres
    password: niewiem
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true
mvc:
  hiddenmethod:
    filter:
      enabled: true

